# IMPORTING ALL REQUIRED LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
from bs4 import BeautifulSoup

## 1) Scraping Content From Wiki Page

In [3]:
# getting data
# get html from wiki page and create soup object
source = requests.get("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M")
soup = BeautifulSoup(source.text, 'lxml')

In [4]:
# scraping table & transforming data into datafrme
table = soup.find('table',{'class':'wikitable sortable'})
table_rows = table.find_all('tr')
data= []
for row in table_rows:
    data.append([t.text.strip() for t in row.find_all('td')])

In [5]:
df = pd.DataFrame(data, columns=['PostalCode', 'Borough', 'Neighbourhood'])
df = df[~df['PostalCode'].isnull()]
df.head(10)

   PostalCode           Borough                                Neighbourhood
1         M1A      Not assigned                                 Not assigned
2         M2A      Not assigned                                 Not assigned
3         M3A        North York                                    Parkwoods
4         M4A        North York                             Victoria Village
5         M5A  Downtown Toronto                    Regent Park, Harbourfront
6         M6A        North York             Lawrence Manor, Lawrence Heights
7         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
8         M8A      Not assigned                                 Not assigned
9         M9A         Etobicoke      Islington Avenue, Humber Valley Village
10        M1B       Scarborough                               Malvern, Rouge

In [6]:
# data cleanup
df.drop(df[df['Borough']=="Not assigned"].index,axis=0, inplace=True)
df.head(10)

   PostalCode           Borough                                Neighbourhood
3         M3A        North York                                    Parkwoods
4         M4A        North York                             Victoria Village
5         M5A  Downtown Toronto                    Regent Park, Harbourfront
6         M6A        North York             Lawrence Manor, Lawrence Heights
7         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
9         M9A         Etobicoke      Islington Avenue, Humber Valley Village
10        M1B       Scarborough                               Malvern, Rouge
12        M3B        North York                                    Don Mills
13        M4B         East York              Parkview Hill, Woodbine Gardens
14        M5B  Downtown Toronto                     Garden District, Ryerson

In [7]:
# grouping all neighborhoods with same postal code

df = df.groupby('PostalCode').agg(lambda x: ','.join(x))

# for cells that have an assigned neighbouhoods,like M7A,assigning their boroughs as their neighbourhood, 

df.loc[df['Neighbourhood']=="Not assigned",'Neighbourhood']=df.loc[df['Neighbourhood']=="Not assigned",'Borough']
df=df.reset_index()
df['Borough']= df['Borough'].str.replace('nan|[{}\s]','').str.split(',').apply(set).str.join(',').str.strip(',').str.replace(",{2,}",",")
df.head(10)

  PostalCode      Borough                                    Neighbourhood
0        M1B  Scarborough                                   Malvern, Rouge
1        M1C  Scarborough           Rouge Hill, Port Union, Highland Creek
2        M1E  Scarborough                Guildwood, Morningside, West Hill
3        M1G  Scarborough                                           Woburn
4        M1H  Scarborough                                        Cedarbrae
5        M1J  Scarborough                              Scarborough Village
6        M1K  Scarborough      Kennedy Park, Ionview, East Birchmount Park
7        M1L  Scarborough                  Golden Mile, Clairlea, Oakridge
8        M1M  Scarborough  Cliffside, Cliffcrest, Scarborough Village West
9        M1N  Scarborough                      Birch Cliff, Cliffside West

In [8]:
# shape of dataframe
print("Shape : ",df.shape)

Shape :  (103, 3)